# Generated by Django 4.2.3 on 2023-07-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='etronic.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('photo1', models.ImageField(upload_to='images/')),
                ('photo2', models.ImageField(upload_to='images/')),
                ('skidki', models.FloatField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='etronic.categoria')),
            ],
        ),
    ]
